# Generated by Django 3.2 on 2021-04-25 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Person Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Person Last Name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Person Middle name')),
                ('disease', models.TextField(verbose_name='Name of disease')),
                ('about', models.TextField(verbose_name='About Person')),
                ('date_of_birth', models.DateTimeField(verbose_name='Person Born Date')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Person Email')),
                ('address', models.CharField(max_length=250, unique=True, verbose_name='Person address')),
                ('url', models.SlugField(unique=True, verbose_name='Url')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10, verbose_name='Status')),
                ('photo', models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.category', verbose_name='Category'), verbose_name='Photo')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('category_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.category', verbose_name='Category')),
            ],
        ),
    ]
